import { createElement } from 'react';
import { GameConfig } from './types';
import PatternGame from './PatternGame';
import SequenceGame from './SequenceGame';
import MazeGame from './MazeGame';
import BugGame from './BugGame';
import ArrowGame from './ArrowGame';
import ColorMatchGame from './ColorMatchGame';
import NumberGame from './NumberGame';
import CountGame from './CountGame';
import ShadowGame from './ShadowGame';
import SortingGame from './SortingGame';
import PianoMaestroGame from './PianoMaestroGame';
import WordProblemGame from './WordProblemGame';
import MathCompareGame from './MathCompareGame';
import MiniSudokuGame from './MiniSudokuGame';
import LogicReasonGame from './LogicReasonGame';
import MathSequenceGame from './MathSequenceGame';
import LogicShapesGame from './LogicShapesGame';
import MathSudokuGame from './MathSudokuGame';
import GeometryDescribeGame from './GeometryDescribeGame';

export const GAMES: GameConfig[] = [
  {
    id: 'pattern',
    title: 'Tìm Quy Luật',
    emoji: '🧩',
    description: 'Quan sát dãy hình, tìm hình còn thiếu theo quy luật',
    color: '#a78bfa',
    gradient: 'from-violet-400 via-purple-400 to-fuchsia-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(PatternGame, p),
  },
  {
    id: 'sequence',
    title: 'Ghi Nhớ Chuỗi',
    emoji: '🎵',
    description: 'Nhớ chuỗi âm thanh phát ra, sau đó lặp lại đúng thứ tự',
    color: '#ec4899',
    gradient: 'from-pink-400 via-rose-400 to-red-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'memory',
    render: (p) => createElement(SequenceGame, p),
  },
  {
    id: 'maze',
    title: 'Robot Tìm Đường',
    emoji: '🧭',
    description: 'Lập trình robot đi đến đích bằng các lệnh di chuyển',
    color: '#3b82f6',
    gradient: 'from-blue-400 via-sky-400 to-cyan-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'coding',
    render: (p) => createElement(MazeGame, p),
  },
  {
    id: 'bug',
    title: 'Tìm Con Bọ',
    emoji: '🐞',
    description: 'Tìm khối lệnh bị sai trong chương trình',
    color: '#f59e0b',
    gradient: 'from-amber-400 via-orange-400 to-red-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'coding',
    render: (p) => createElement(BugGame, p),
  },
  {
    id: 'arrow',
    title: 'Đọc Chỉ Dẫn',
    emoji: '🎯',
    description: 'Nhìn chuỗi mũi tên và chọn đáp án giống hệt',
    color: '#10b981',
    gradient: 'from-emerald-400 via-green-400 to-lime-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(ArrowGame, p),
  },
  {
    id: 'colormatch',
    title: 'Ghép Màu',
    emoji: '🎨',
    description: 'Tìm màu/emoji còn thiếu để hoàn thành quy luật màu',
    color: '#06b6d4',
    gradient: 'from-cyan-400 via-teal-400 to-emerald-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(ColorMatchGame, p),
  },
  {
    id: 'number',
    title: 'Dãy Số Bí Ẩn',
    emoji: '🔢',
    description: 'Tìm số tiếp theo trong dãy số theo quy luật',
    color: '#6366f1',
    gradient: 'from-indigo-400 via-blue-400 to-violet-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(NumberGame, p),
  },
  {
    id: 'count',
    title: 'Đếm & So Sánh',
    emoji: '🧮',
    description: 'Đếm số phần tử, so sánh và tính toán',
    color: '#84cc16',
    gradient: 'from-lime-400 via-green-400 to-teal-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(CountGame, p),
  },
  {
    id: 'shadow',
    title: 'Ghép Bóng',
    emoji: '🪞',
    description: 'Tìm hình phản chiếu đúng với hình gốc',
    color: '#0ea5e9',
    gradient: 'from-sky-400 via-blue-400 to-indigo-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(ShadowGame, p),
  },
  {
    id: 'sorting',
    title: 'Xếp Theo Thứ Tự',
    emoji: '📊',
    description: 'Sắp xếp các phần tử theo thứ tự đúng',
    color: '#14b8a6',
    gradient: 'from-teal-400 via-cyan-400 to-sky-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(SortingGame, p),
  },
  {
    id: 'piano',
    title: 'Nhạc Trưởng Nhí',
    emoji: '🎹',
    description: 'Nghe và chơi piano theo giai điệu - Bé trở thành nhạc trưởng!',
    color: '#a855f7',
    gradient: 'from-purple-400 via-fuchsia-400 to-pink-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'music',
    render: (p) => createElement(PianoMaestroGame, p),
  },
  // Toán tư duy - FMO/HKIMO style
  {
    id: 'wordproblem',
    title: 'Toán Có Lời Văn',
    emoji: '📚',
    description: 'Giải bài toán có lời văn - Tư duy như FMO',
    color: '#f97316',
    gradient: 'from-orange-400 via-amber-400 to-yellow-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(WordProblemGame, p),
  },
  {
    id: 'mathcompare',
    title: 'So Sánh Số',
    emoji: '⚖️',
    description: 'So sánh, tìm max/min, điền phép tính',
    color: '#d97706',
    gradient: 'from-amber-400 via-yellow-400 to-orange-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(MathCompareGame, p),
  },
  {
    id: 'minisudoku',
    title: 'Mini Sudoku 4×4',
    emoji: '🧩',
    description: 'Điền số 1-4 vào ô trống theo quy luật',
    color: '#0891b2',
    gradient: 'from-cyan-400 via-sky-400 to-blue-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(MiniSudokuGame, p),
  },
  {
    id: 'logicreason',
    title: 'Suy Luận Logic',
    emoji: '🧠',
    description: 'Suy luận: đúng/sai, hình khác, số sai trong dãy',
    color: '#7c3aed',
    gradient: 'from-violet-400 via-purple-400 to-indigo-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(LogicReasonGame, p),
  },
  {
    id: 'mathseq',
    title: 'Dãy Số Toán',
    emoji: '🔢',
    description: 'Tìm số ở giữa, số thiếu, số chẵn/lẻ - Tư duy HKIMO',
    color: '#be185d',
    gradient: 'from-pink-400 via-rose-400 to-red-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(MathSequenceGame, p),
  },
  {
    id: 'logicshapes',
    title: 'Hình Logic',
    emoji: '🔷',
    description: 'Đếm đỉnh, xoay hình, đối xứng - Tư duy hình học',
    color: '#0369a1',
    gradient: 'from-blue-400 via-indigo-400 to-purple-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'logic',
    render: (p) => createElement(LogicShapesGame, p),
  },
  {
    id: 'mathsudoku',
    title: 'Toán Sudoku',
    emoji: '➕',
    description: 'Sudoku cộng trừ - điền số sao cho mỗi hàng và cột đều đúng',
    color: '#15803d',
    gradient: 'from-green-400 via-yellow-400 to-orange-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(MathSudokuGame, p),
  },
  {
    id: 'geometrydescribe',
    title: 'Toán Mô Tả Hình',
    emoji: '📐',
    description: 'Đọc mô tả tính chất hình học, tìm hình đúng',
    color: '#0f766e',
    gradient: 'from-teal-400 via-emerald-400 to-lime-400',
    totalLevels: 100,
    unlockThreshold: 0,
    category: 'math',
    render: (p) => createElement(GeometryDescribeGame, p),
  },
];

export function getGame(id: string): GameConfig | undefined {
  return GAMES.find(g => g.id === id);
}